### PR TITLE
Calculate the optimal preview size based on the view size

### LINKED ISSUE #105: Library fails to select best preview size when not in fullscreen
First of all: This is a nice library! Thank you so much! 

I'm currently trying to include the ScannerView in one of my projects and everything works fine, except the library does not seem to select the best matching aspect ration for the camera preview.

I don't want to show the ScannerView fullscreen, instead I want to embed it in my layout. The space available for the ScannerView roughly matches a 4:3 aspect ratio. There is a matching `Camera.Size` for 4:3 available, but still the ScannerView selects the 16:9 size.

I think I also found the reason for this miscalculation: Since 1c0c74f9e445a5dea0cdc87484c89be651dbdcdf, you adjust the surface size based on the view's dimensions, but you still try to calculate the best matching camera preview size based on the screen resolution.

`CameraPreview.java` line 192:
```
int w = screenResolution.x;
int h = screenResolution.y;
if (DisplayUtils.getScreenOrientation(getContext()) == Configuration.ORIENTATION_PORTRAIT) {
    w = screenResolution.y;
    h = screenResolution.x;
}
```

You probably have to use `getWidth()`/`getHeight()` instead of the screen resolution here as well.

Perhaps I'll find the time to create a Pull Request with the fix, but if you want to fix it yourself, go ahead!

### PR DESCRIPTION
**Pull request by dmo60**
This should fix #105.

Please let me know, if you see any problems here.

### CODE REVIEW

**Comment by mincel** [comment]
This is a great library! Thank you!

I am currently developing an application with a full screen ZXingScannerView. It has an overlay button bar to control flash and some other things at the bottom. After this merge unfortunately I am not able to make camera preview full screen. Am I missing something?

File: core/src/main/java/me/dm7/barcodescanner/core/CameraPreview.java [hunk 1]
```diff
@@ -188,14 +187,8 @@ public int getDisplayOrientation() {
         }
 
         List<Camera.Size> sizes = mCamera.getParameters().getSupportedPreviewSizes();
-        Point screenResolution = DisplayUtils.getScreenResolution(getContext());
-        int w = screenResolution.x;
-        int h = screenResolution.y;
-        if (DisplayUtils.getScreenOrientation(getContext()) == Configuration.ORIENTATION_PORTRAIT) {
-            w = screenResolution.y;
-            h = screenResolution.x;
-        }
```
Comment (OzTK) [inline core/src/main/java/me/dm7/barcodescanner/core/CameraPreview.java]: I think you shouldn't have deleted the orientation condition as it now gives a wrong target ratio in portrait mode

Comment (dm77) [inline core/src/main/java/me/dm7/barcodescanner/core/CameraPreview.java]: @OzTK agreed. Thanks for your pull request. Just merged in. 
@dmo60 Merging the pull request could also mean back to square one.
